# Generated by Django 6.0.7 on 2026-08-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=150, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ['term'],
            },
        ),
    ]
