# Generated by Django 6.0.7 on 2026-08-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_glossaryterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, default='Slug to add')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='posts', to='webapp.type'),
        ),
    ]
